### ISSUE TITLE
Execute-Assembly Hangs for Some Assemblies

### ISSUE THREAD

**Issue by djhohnstein** [xorrior/poseidon#7]
Some assemblies hang and never quit their thread. To kill them requires a jobkill. Investigate why this is occurring.

**Comment by djhohnstein** [comment]
https://github.com/caseysmithrc/AssemblyLoader
https://github.com/matiasinsaurralde/go-dotnet

These should serve as starting points for proper .NET Framework CLR hosting.

**Comment by xorrior** [comment]
Sir, this module no longer exists. Thank you and have a wonderful day
